name: task_07_backdrop
description: Work in progress for a Unit Converter app.


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  backdrop: ^0.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
